### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by KalpanaChetan** [aliakseis/FVD#1]

**Comment by KalpanaChetan** [comment]
![Screenshot (8).png](https://user-images.githubusercontent.com/112402936/202494585-18c7307b-a313-45a1-8846-70e6f7095f6b.png)

**Comment by aliakseis** [comment]
Hi,
Most propably the matching Python installation is missing. For example this installation can be used:
https://www.python.org/ftp/python/3.9.13/python-3.9.13.exe
You can either choose adding the Python executables location to the PATH env. var.  while doing the above installation or create a CMD file for starting the FVD application that adds the Python executables location to the PATH beforehand.

Also it makes sense turning logging on.
Open the next next branch in REGEDIT:
HKEY_CURRENT_USER\SOFTWARE\FVD\FVD
Add the "LoggingEnabled" item to it, either REG_DWORD 1 or REG_SZ "true"
Now you can observe FVD*.txt logs in the C:\Users\<User>\Local Settings\FVD\FVD folder.

**Comment by KalpanaChetan** [comment]
Now I have installed python but the problem is not solved

**Comment by aliakseis** [comment]
Could you share what you have in the log file?

**Comment by aliakseis** [comment]
Also your query looks strange. Could you please try something like the one on the demo image?

**Comment by KalpanaChetan** [comment]
> Also your query looks strange. Could you please try something like the one on the demo image?
> 




My query is a youtube url

**Comment by KalpanaChetan** [comment]
> > Also your query looks strange. Could you please try something like the one on the demo image?
> > 
> 
> 
> 
> 
> My query is a youtube url





please watch both videos


https://user-images.githubusercontent.com/112402936/202903020-7dd56def-335f-4af3-bf6e-1ad0c9cdfb1e.mov



https://user-images.githubusercontent.com/112402936/202903101-f36b2020-ca66-49a4-94d9-8c925dc7bf55.mov

**Comment by aliakseis** [comment]
According to the second video it seems to be working, you just need to wait for response for a few seconds.
To use a Youtube url you need to either drag and drop it or paste with the second tab (Downloads) selected.

**Comment by aliakseis** [comment]
Please either hit the "Download" part of the button or choose a resolution from the popup list.

**Comment by KalpanaChetan** [comment]
> Could you share what you have in the log file?


please tell me which file to upload

and how to upload

![Screenshot (13).png](https://user-images.githubusercontent.com/112402936/202903318-43fccd15-6add-44ca-b13d-7cfd158eb516.png)

**Comment by KalpanaChetan** [comment]
> According to the second video it seems to be working, you just need to wait for response for a few seconds.
> To use a Youtube url you need to either drag and drop it or paste with the second tab (Downloads) selected.
> 



Yes but app not proper working

the second video was recorded earlier
and then the first video recorded

**Comment by aliakseis** [comment]
The first video - it looks like it is just waiting for the query to finish.
According to the second video - it properly obtains the list of videos, you just need to start a video watching / downloading...

**Comment by aliakseis** [comment]
The search query underneath is not that fast by itself - it can run up to ~ 10 secs depending.

**Comment by aliakseis** [comment]
![hit](https://user-images.githubusercontent.com/11851670/202908305-27b73d28-a2fa-4a87-b409-f1455efb24aa.png)

Please just click somewhere where the arrows point.

**Comment by KalpanaChetan** [comment]
> ![hit](https://user-images.githubusercontent.com/11851670/202908305-27b73d28-a2fa-4a87-b409-f1455efb24aa.png)
> 
> Please just click somewhere where the arrows point.

Thanks you

**Comment by KalpanaChetan** [comment]
![Screenshot (14).png](https://user-images.githubusercontent.com/112402936/202909188-8c087f05-d8f3-4215-badf-79bec4230a26.png)

**Comment by KalpanaChetan** [comment]
> ![Screenshot (14).png](https://user-images.githubusercontent.com/112402936/202909188-8c087f05-d8f3-4215-badf-79bec4230a26.png)

please tell me how to upload

**Comment by aliakseis** [comment]
This is not a log file.
I am sorry, for now you need to turn on log files generation manually by editing the registry as described above.
Have you tried to start a video?
Probably there is no need to bother uploading logs if it works?

**Comment by KalpanaChetan** [comment]
Only 720p

**Comment by KalpanaChetan** [comment]
![Screenshot (16).png](https://user-images.githubusercontent.com/112402936/203036057-52bff0d2-a6cf-4be9-ae58-6505e9fe9a20.png)




99.9% ?

**Comment by KalpanaChetan** [comment]
![Screenshot (17).png](https://user-images.githubusercontent.com/112402936/203038534-c9b9b23e-5b83-4e55-b457-b854772a1f82.png)

Please make full video player

**Comment by KalpanaChetan** [comment]
![Screenshot (18).png](https://user-images.githubusercontent.com/112402936/203038638-05295119-4b76-4ca0-90b3-f19de3384bd5.png)

Youtube video  url working

**Comment by aliakseis** [comment]
![paste](https://user-images.githubusercontent.com/11851670/203046809-bf54fce4-d8d1-4bc9-98a3-748ff7aa418e.png)

You can paste or drop not only urls but also list of urls.

Invoke Alt-Enter to enter Full Screen mode.

**Comment by KalpanaChetan** [comment]
> ![paste](https://user-images.githubusercontent.com/11851670/203046809-bf54fce4-d8d1-4bc9-98a3-748ff7aa418e.png)
> 
> You can paste or drop not only urls but also lists of urls.
> 
> Invoke Alt-Enter to enter Full Screen mode. 

Thanks for full screen mode

**Comment by KalpanaChetan** [comment]
> ![paste](https://user-images.githubusercontent.com/11851670/203046809-bf54fce4-d8d1-4bc9-98a3-748ff7aa418e.png)
> 
> You can paste or drop not only urls but also lists of urls.
> 
> Invoke Alt-Enter to enter Full Screen mode. 

Copy paste not working in download tab (please see video)

**Comment by KalpanaChetan** [comment]
I play video number 2
After that I play video number 3
It just pause video number 2
It does not play video number 3
 https://user-images.githubusercontent.com/112402936/203051456-71c77d99-7014-4db9-8020-1a0b6de5ed60.mov

**Comment by KalpanaChetan** [comment]
> > ![paste](https://user-images.githubusercontent.com/11851670/203046809-bf54fce4-d8d1-4bc9-98a3-748ff7aa418e.png)
> > 
> > You can paste or drop not only urls but also lists of urls.
> > 
> > Invoke Alt-Enter to enter Full Screen mode. 
> 
> Copy paste not working in download tab (please see video)



https://user-images.githubusercontent.com/112402936/203054215-8e3510f9-af5d-4f9e-958d-097d72b57924.mov

**Comment by KalpanaChetan** [comment]
You mean 

Ctrl a 

Ctrl c 

And paste

**Comment by KalpanaChetan** [comment]
> You mean 
> 
> Ctrl a 
> 
> Ctrl c 
> 
> And paste 

Because only ctrl a and paste not working
I check it

**Comment by aliakseis** [comment]
Yes, you are right

**Comment by KalpanaChetan** [comment]
> Only 720p?
> 
> 
> Playlist downloader?
> 
> Why both options (please see video)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> https://user-images.githubusercontent.com/112402936/203034971-062cb336-c08b-46b9-99d9-e8e6ea27d86c.mov





Sorry 

I checked the setting and found that only youtube option is selected

For this reason
 if I uncheck the youtube option

this automatically uncheck the option for all video sites

**Comment by aliakseis** [comment]
Basically this video sites stuff is a stub, not sure if it will be implemented at all..

**Comment by aliakseis** [comment]
A kind of old abandoned project that I decided to revive and share...

**Comment by KalpanaChetan** [comment]
> > Only 720p?
> > 
> > 
> > Playlist downloader?
> > 
> > Why both options (please see video)
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > https://user-images.githubusercontent.com/112402936/203034971-062cb336-c08b-46b9-99d9-e8e6ea27d86c.mov
> 
> 
> 
> 
> 
> Sorry 
> 
> I checked the setting and found that only youtube option is selected
> 
> For this reason
>  if I uncheck the youtube option
> 
> this automatically uncheck the option for all video sites
> 


This is not a problem (video n2) 
I just told you

**Comment by KalpanaChetan** [comment]
Thanks for reviving this project and sharing it

**Comment by aliakseis** [comment]
![2022_11_21_18_17_09_Settings](https://user-images.githubusercontent.com/11851670/203091326-42b54d6f-611e-4e55-aea1-57d1422af84a.png)

I mean this stuff.

**Comment by KalpanaChetan** [comment]
> ![2022_11_21_18_17_09_Settings](https://user-images.githubusercontent.com/11851670/203091326-42b54d6f-611e-4e55-aea1-57d1422af84a.png)
> 
> I mean this stuff.

Ok
